### ISSUE TITLE
Remove @JStaches

### ISSUE THREAD

**Issue by agentgt** [jstachio/jstachio#15]
Having multiple `@JStache` on a single model is problematic for the JStachio runtime as well as complicates the annotation processor.

**Comment by agentgt** [comment]
@sviperll I think a better solution for multiple JStaches is probably allowing custom annotations. 

```java
@Text
@Html
record SomeModel {}
```

Then `@Text` might be defined like:

```java
@JStacheConfig(naming=@JStacheName(suffix="text.mustache"), contentType=PlainText.class)
public @interface Text {
}
```

Then in all the template finding mechanisms you just say which annotation you want to use.

What do you think?

**Comment by sviperll** [comment]
I think the question is how exactly are we going to select which annotation to use in template finding mechanisms... I think I would need some practice with such system to arrive at the conclusion if it's a good way to go.

For now, I'm a little concerned about any customization of "template finding mechanisms", because the promise of the project was always to catch errors early and everywhere. Customization of template finding can result in errors that are only going to be caught at run-time...

Another comment is that if we are going to introduce "meta-annotations" then I would like `JStacheFormatterTypes` to be "meta-annotation", so that it's easy to consolidate this configuration in a single annotation, and then easily use this annotation from everywhere, so that nothing is duplicated, but it's easy to jump from usage to definition.

Another comment is that we may probably want to have explore method-level annotations, like:

````java
@JStacheTemplateRegistry
interface TemplateRegistry {
    @JStache(template="hello.mustache")
    Template helloWorld(String message, List<Person> people);

    @JStache(template="goodbye.mustache")
    Template goodBye(List<Person> people);
}
````

and have something like:

````java
TemplateRegistry registry = JStachio.getTemplateRegistry(TemplateRegistry.class);
registry.helloWorld("Hello", somePeople).execute(System.out);
````

In this world we may need no duplicated annotations, because it may be cheap enough to have multiple different methods for different content-types or languages/locales.

**Comment by agentgt** [comment]
I had the TemplateRegistry idea before even using static-mustache for my handlebars version as MapStruct and a few others do this model.

The reason I didn't was the amount of work, the advent of records, and I figured you first needed to do what you were already doing which is put everything in some container which is basically how all other templating engines work albeit with `Map<String, Object>`.

I also was going to allow methods return `String` or take `Appendable`/ `StringBuilder` instead of just the `Template`.

But I agree that is a nicer alternative to make it easy for template combinatorics on the same types of models without collision issues.

**Comment by agentgt** [comment]
> For now, I'm a little concerned about any customization of "template finding mechanisms", because the promise of the project was always to catch errors early and everywhere. Customization of template finding can result in errors that are only going to be caught at run-time...

As for the above. I'm not sure what the concern is. Compiler errors will still happen. If anything `TemplateRegistry` is just as likely to fail as go lookup some template for some model (as to both cases of using the generated classes directly which I assume in both cases will be possible). If someone is worried the models are not the right type they can make wrapping libraries and use `JStacheInterfaces` to enforce the models implement some interface.


Also I'm remembering more on why I stopped the TemplateRegistry idea and I remember that Rocker and JTE had to abandon that model for Spring MVC (or provide not type safe hack) as it is nontrivial to call those methods from Spring MVC (e.g. its easier to inject a single model then inject method parameters as well as java only allows a single return type).

**Comment by agentgt** [comment]
> For now, I'm a little concerned about any customization of "template finding mechanisms", because the promise of the project was always to catch errors early and everywhere. Customization of template finding can result in errors that are only going to be caught at run-time...

Actually to be fair I'm not really sure what you meant by this (so ignore my previous comment). Currently the only runtime logic that is most of JStachio module is go find a template for this model. This can happen even statically instead of the ServiceLoader.

Why do we need the above? Same reason for the TemplateRegistry. People do not always want to have references of generated code but rather their own types. 

The only runtime issue is you pass in an instance of some object that is not a JStache model.

OR the template was not generated (which is almost always an incremental compiler issue or some other hot reloader) in which case there are various **optional** fallback  mechanism in which a reflection based template is generated which is basically all of the configuration that would normally be static is now loaded up dynamically (that is why TemplateInfo exists). Currently that meta data model is fed to JMustache (optional).

ALSO the template finding needs to be powerful because of DI. Its not really template finding btw but instance creating. In fact DI gives us even more safety of preventing the aforementioned using a model that isn't a model: https://github.com/jstachio/jstachio/issues/10#issuecomment-1341491052

```
@Autowired ViewFactory<HelloWorldModel> view;
```

Spring will fail immediately on boot up if HelloWorldModel isn't a real JStache.

**Comment by sviperll** [comment]
> The only runtime issue is you pass in an instance of some object that is not a JStache model.

That's what I mean. For now we have a simple definition about what JStache-model is: anything that has `@JStache` annotation, but with custom definitions this becomes not so simple and it may be easier to pass something that is actually not a JStache model for given configuration.

With hypothetical `@Text` and `@Html` we may have something like:

````java
@Text
@Html
@JStache(path="main/some-model")
record SomeModel() {}
````

And jstachio compiler will check everything about both: `main/some-model.text.mustache` and `main/some-model.html.mustache` templates.

Now what if we have:

````java
@Html
@JStache(path="main/another-model")
record AnotherModel() {}
````

Here only `main/another-model.html.mustache` is compiled.

What if I then want to render text, I'd do something like:

````java
JStachio.forConfig(Text.class).execute(new SomeModel());
JStachio.forConfig(Text.class).execute(new AnotherModel()); // This will fail because AnotherModel has no `@Text` annotation
````

So for me it seems like the problem that seem trivial before, has become not so trivial and it is easier to pass wrong combination of configuration and model, because there are more combinations...

**Comment by agentgt** [comment]
Oh I see now what you mean! Yeah its worse then just having JStaches because at least with the old JStaches I could do a compile time check on the name collision issue (which even if I didn't would just fail at compile time).

I was going to keep JStaches and have the template finding with something like:

```java
List<Template<T>> jstachio.findTemplates(Class<T> modelClass);
```

The default being the first JStache in the JStaches array if there is a JStaches annotation.

**Comment by agentgt** [comment]
I guess to make it easier for the template explosion and reuse of templates I could allow the enclosing type to provide config:


```java
@JStacheConfig(/* some config */)
class final TemplateRegistry {

    @JStache(template="hello.mustache")
    record HelloWorld(String message, List<Person> people){}

    @JStache(template="goodbye.mustache")
    record GoodBye(List<Person> people){}

    @JStachConfig(contentType=PlainText.class)
    @JStache(template="hello.txt.mustache")
    record HelloWorldText(String message, List<Person> people){}
}
```

Right now it goes `class > package > module` but it probably should be `class > enclosing class > package > module`.

Yeah you create multiple records instead of methods but records have more power than a method (because they can implement interfaces) and are almost the same amount of syntax burden.

**Comment by sviperll** [comment]
I'm not sure how big the problem may be. I've said that we need some actual experience to find it out...

**Comment by sviperll** [comment]
I like your example with the outer class, but note how class with lots of records looks almost exactly as interface with methods :)
