### ISSUE TITLE
Spring sample is serving HTML with no content-type

### ISSUE THREAD

**Issue by dsyer** [jstachio/jstachio#172]
I think this is a regression because I'm pretty sure it used to work.

**Comment by agentgt** [comment]
Servlet or webflux?

**Comment by agentgt** [comment]
I think I missed checking some of the endpoints for content type. I will see if I can get some integration testing but the more alarming thing is the main controller (`/`):

https://github.com/jstachio/jstachio/blob/ede393ab31f841519fae8571b5a201ff5a6e2ec4/opt/jstachio-spring-example/src/main/java/io/jstach/opt/spring/example/hello/HelloController.java#L54

You would think it would use the message converter right because of the `ResponseBody` annotation but instead it using the ModelAndView pipeline.

Apparently it does not use the message converter (had to use debugger to figure this out) it sees that it implements a `View` (we should probably just make two models). Remember I made `HelloModel` implement `View` to show case mixins.

I wonder if that is a bug in Spring. It seems `@ResponseBody` should take precedence?

Of course the second issue is why the `View` version is not writing the content type.

The other endpoints like `/repsonseEntity` and sort of `/templateModel` appear to set the content type as they are using the Message Converter code.

**Comment by dsyer** [comment]
Isn't it because you asked JStachio to generate `View` implementations as the model type? It's kind of mixing metaphors - the sample is trying to show both renderers.

**Comment by agentgt** [comment]
> Isn't it because you asked JStachio to generate View implementations as the model type? It's kind of mixing metaphors - the sample is trying to show both renderers.

That is correct. I was just wondering if that is correct behavior on Spring's part and it probably is or was decided long ago. The View stuff is older than the MessageConverter so it makes since.

I'm going make `HelloModelAndView` to make the distinction clear for both Spring and users.

**Comment by agentgt** [comment]
Do you think we should always generate HTML for controllers that return JStachio models?

I say that because if the Accept type is not text/html Jackson apparently kicks off.

I can see a use case for that but its more like the 20% use case and it seems dangerous.

**Comment by agentgt** [comment]
Looks like I can't really control it. The order is based on the List of MessageConverters.

I suppose once we figure auto configure we can add it first. You will see my change in the example app once I commit to see what I mean.

**Comment by agentgt** [comment]
Apparently multi-line string literals are padded with empty bytes!

I can't google the reason for this but it blows my mind.

```java
	static final String SLASH_BODY = """
			<!doctype html>
			<html lang="en">
			  <head>
			    <meta charset="utf-8">
			    <meta name="viewport" content="width=device-width, initial-scale=1">
			    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css">
			    <title>Hello, Spring Boot is now JStachioed!!</title>
			  </head>
			  <body>
			    <main class="container">
			      <h1>Spring Boot is now JStachioed!</h1>
			    </main>
			  </body>
			</html>""";
```

That should be 414 bytes if converted to UTF-8 but its like 1100.
