### ISSUE TITLE
Apt template resolution from IDEA

### ISSUE THREAD

**Issue by taypo** [jstachio/jstachio#221]
I was trying Dave Syer's [template demo](https://github.com/dsyer/java-template-demo/tree/jstachio) and got the following error while building inside IDEA.
This with version 1.3.0 of jstachio. 1.2.0 failed with a similar error with a different path in the log.

```
/Users/bahadir/dev/personal/java-template-demo/src/main/java/demo/DemoModel.java:6:8
java: java.io.IOException: Failed to find template resource: 'templates/index.mustache'. Tried the following locations: 'file:/Users/bahadir/dev/personal/java-template-demo/target/classes/templates/index.mustache', '/Users/bahadir/dev/src/main/resources/templates/index.mustache'

```

First path seems to be correct, though I'm not sure about the `file:` prefix. Second path is definitely missing 2 directories in the middle. If you delegate build to maven from IDEA, everything works.

Thanks

**Comment by agentgt** [comment]
I have been meaning to boot up IDEA on this project to test (I do use it from time to time).

Ironically I have been using Eclipse and VSCode because there usually the more problematic ones.

The first one is CLASS_OUTPUT. You can ignore the URI portion of it.

The reason it does not resolve is because IDEA has not copied over the resources yet or does not seem them for whatever reason. Eclipse has a similar problem.

Do you have incremental compiling turned on?

The second one is a guessing attempt based on where the APT filer thinks its CWD is.

What I probably need to do is use `StandardLocation.SOURCE_PATH` for IDEA (which does not work for Eclipse or Maven)... fun am I right?

Anyway you can see that logic here 
https://github.com/jstachio/jstachio/blob/main/compiler/apt/src/main/java/io/jstach/apt/TextFileObject.java


I'll have a fix tonight or tomorrow.


In the meantime see or read: https://jstach.io/jstachio/io.jstach.jstache/io/jstach/jstache/JStache.html#RESOURCES_PATH_OPTION

I need to improve the overview to point to that.

**Comment by taypo** [comment]
I've read `TextFileObject.java` before I filed this, I don't envy you :)

**Comment by agentgt** [comment]
Darn I'm having a hard time reproducing. Perhaps there are some symlinks (aka `ln -s`) ?

**Comment by taypo** [comment]
No symlinks in my path. Steps to reproduce:
1. clone https://github.com/dsyer/java-template-demo.git
2. checkout jstachio branch
3. change version to 1.3.0 in pom.xml
4. open in IDEA and let it load the project
5. hit Cmd+F9 to build using the ide, and you'll get the error.

If you use the maven tool window to build, or your IDEA is set to delegate build to maven, then it works without issue. Maybe check here to see if your build is delegated to maven:
https://www.jetbrains.com/help/idea/delegate-build-and-run-actions-to-maven.html#delegate_to_maven

**Comment by agentgt** [comment]
I think the critical step I missed is upgrade to 1.3.0

**Comment by agentgt** [comment]
I tried upgrading 1.3.0 and made sure delegate to maven is off.

I tailed the intellij log file as well as checked build output.

I only get one warning:

> Output path /Users/agent/projects/java-template-demo/target/generated-sources/annotations intersects with a source root. Only files that were created by build will be cleaned.

I'm not sure what that means exactly. Maybe that is the issue? Is this CE or Ultimate?

----

macOs

IntelliJ IDEA 2023.2 (Community Edition)
Build #IC-232.8660.185, built on July 26, 2023
Runtime version: 17.0.7+7-b1000.6 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4
Metal Rendering is ON
Registry:
    ide.experimental.ui=true


Kotlin: 232-1.9.0-IJ8660.185

**Comment by taypo** [comment]
Its CE. Anything I can do to help?

**Comment by agentgt** [comment]
> Its CE. Anything I can do to help?

I guess where do you see the error? Is it in the Build Output window or is in the actual intellij log file?

Does the error eventually go away?

I assume you are on macOS. Intel or Arm (I know its highly unlike this matters)?

Do you have another machine or vm image you could try?

I don't have intellij in front of me at the moment and won't be able to test till tonight.

**Comment by taypo** [comment]
It's in the build output. I'm using arm Mac. I can try on an intel mac later today. Let me see if I have a VM lying around.

**Comment by taypo** [comment]
I've tried with a windows and ubuntu VM, both had the same error.

**Comment by agentgt** [comment]
Can you copy the build output?

**Comment by agentgt** [comment]
I switched to JDK 17 and it happened.

**Comment by agentgt** [comment]
@taypo Can you try using JDK 20 and see if the problem goes away on your end while I figure out what hack I can put in?

**Comment by taypo** [comment]
Yeah, it worked now with JDK 20. 
(nothing to be sorry about, I thought this was an IDEA issue, so didn't think to report my JDK version)

**Comment by agentgt** [comment]
I found the problem and fixed it. The fallback was thinking it was Gradle because Intellij has Gradle somewhere in its execution command.

**Comment by agentgt** [comment]
@taypo  in Release 1.3.1 . Thanks for the help!
