### ISSUE TITLE
Constant deduplication in renderer

### ISSUE THREAD

**Issue by bitfist** [jstachio/jstachio#266]
I was playing around to get a better understanding of the generated renderer and noticed that this template
```mustache
<head>
    {{#cssFiles}}
    <link rel="stylesheet" href="{{source}}" />
    {{/cssFiles}}
    {{#jsFiles}}
    <script type="application/javascript" src="{{source}}" />
    {{/jsFiles}}
</head>
```

produces these constants in the renderer
```java
    private static final byte[] TEXT_0 = (
    "<head>\r\n").getBytes(TEMPLATE_CHARSET);
    private static final byte[] TEXT_1 = (
    "    <link rel=\"stylesheet\" href=\"").getBytes(TEMPLATE_CHARSET);
    private static final byte[] TEXT_2 = (
    "\" />\r\n").getBytes(TEMPLATE_CHARSET);
    private static final byte[] TEXT_3 = (
    "    <script type=\"application/javascript\" src=\"").getBytes(TEMPLATE_CHARSET);
    private static final byte[] TEXT_4 = (
    "\" />\r\n").getBytes(TEMPLATE_CHARSET);
    private static final byte[] TEXT_5 = (
    "</head>").getBytes(TEMPLATE_CHARSET);
```

`TEXT_2` and `TEXT_4` are identical, resuing `TEXT_2` could save a couple of bytes and instructions.

Changing `io.jstach.apt.internal.context.VariableContext#addTextCode` to
```java
	public String addTextCode(String textCode) {
		var codes = textCodes();
		int index = codes.indexOf(textCode);

		if (index < 0) {
			index = codes.size();
			codes.add(textCode);
		}

		return TEXT + "_" + index;
	}
```
seems to do the trick.

I am currently on a Windows 10 machine and unfortunately cannot run the tests (issues with line endings), but using the modified template compiler locally produces the expected renderer (`TEXT_2` is used twice).

**Comment by agentgt** [comment]
Oh yeah I guess bytes are probably not interned or elided like string.

**Comment by agentgt** [comment]
Thank you for the contribution @bitfist !

Besides adding your enhancement I made it so when you checkout on windows the line endings of the mustache files should be preserved.

**Comment by zimmi** [comment]
@agentgt Just some random thoughts on another avenue for optimization, I thought I'd write it down:
Did you consider / is it possible to store all static pieces of all templates that are compiled together in a single `byte[]` and then access them by offsets? Imagined benefits:
1. less pointer chasing of individual arrays
1. less object headers for the individual arrays
1. reduce total `<clinit>` time by only loading the generated blob from a file, skipping the string decoding
1. easy feedback on the amount of heap reserved for template caching (could also mmap the blob to reduce this)

The deduplication of individual pieces from this ticket could also be performed globally on the blob (updating offsets).

**Comment by agentgt** [comment]
@zimmi @bitfist 

Yes I thought about doing this. Even the byte deduplication that @bitfist found I was planning on doing but did not for do for different reasons but some overlapping. The byte deduplication avoidance was more about keeping to keep the code easier to read and diff of the generated file down which in hindsight was dumb because most people will not be checking in the generated files.

For the byte deduplication I was planning more of.

```
static final byte[] TEXT_4 = TEXT_2;
```

But I like @bitfist solution better because it is simpler and they already did it for me. Thanks BTW @bitfist.


Now for the single byte array I tried doing something like that several years ago on an internal forked version of JMustache. It is a little different because it was runtime generated so perhaps this should be revisited.

Regardless the results were surprisingly slower based on JMH benchmarks. 

I thought Rocker also did similar and then reverted IIRC but I cannot easily figure that out since it is generated code. That is might be confusing it with another templating engine. Perhaps https://htmlflow.org/ .

Anyway we should try it again. Luckily unlike Rocker or JTE I left an API hole for us to do it:

https://jstach.io/jstachio/io.jstach.jstachio/io/jstach/jstachio/Output.EncodedOutput.html#write(byte%5B%5D,int,int)

Javadoc comment:

> Analogous to [OutputStream.write(byte[], int, int)](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/OutputStream.html#write(byte%5B%5D,int,int)). Generated templates do not call this method as great care as to be taken to preserve the encoding. **It is only provided in the case of future found optimizations and is not currently required**.

Obviously a giant array with another int array for offsets will probably use less static memory (I'm blanking on what that memory is called... not permgen...) as well as to your other points.

The question is if it slows down actual template rendering.

Luckily we can test that here: https://github.com/agentgt/template-benchmark

We just take the generated code from this guy: https://github.com/agentgt/template-benchmark/blob/utf8/src/main/java/com/mitchellbosecke/benchmark/utf8/JStachioUtf8.java

And alter the generated code manually so that it has your array idea and add it as another template engine in the utf8 package.
 
At the moment I don't have time to do this but I can help you if you plan on testing this.

Once we know it doesn't impact perf and readability that much I think we could probably do this and thanks for bringing it up!

**Comment by agentgt** [comment]
> I suspected that you tried this already, mad props for the foresight of leaving enough API space for further optimizations!

Never assume 😄 because most of the time have not tried and I'm not always that bright. I rather people participate and tell me things I have tried or thought about than be too afraid too (I'm not saying you were but it is a fear of mine).

Thats why I kind of didn't want to lead with oh yeah I was going to do constant deduplication when @bitfist reported this because then people will feel like "he probably already knows" or "he knows the better way".

I guess what I'm saying is never want any hesitation on filing bugs or asking question or suggestions. I have seen that in lots of other projects were it is terrifying to even ask a question and I think that is wrong.

I am curious to see the results and if you don't have time I will eventually retry it especially given the differences I have noticed with ARM64.
