### ISSUE TITLE
@JStachePath should apply to sub-packages as well

### ISSUE THREAD

**Issue by dsyer** [jstachio/jstachio#69]
It's annoying to have to duplicate create additional `package-info.java` all with identical `@JStachePath` configuration. Couldn't they inherit from parent packages somehow?

**Comment by agentgt** [comment]
Per the doc: https://jstach.io/jstachio/io.jstach.jstache/io/jstach/jstache/JStacheConfig.html

> While package hiearchy may seem natural for cascading config this library does not do it. Package hiearchy does NOT matter to this library! Resolution will NOT check up parent package directories. If you do not want to copy config to each package it is recommended you use module annotations.

(which is good you brought it up because I just noticed the spelling error of hierarchy) 

The idea is if you want global config is to use `module-info.java`.

You can also use enclosing classes.

The problem is packages are not really hierarchical. For example if you call any `getEnclosingElement` via Java reflection or TypeMirror/TypeElement API is not going to go up the package directories. You just go to the package that your class is currently in and then if you call it again you go to the module.  

While I could mangle the package name to go up the directories there are an ass load of issues that come up with doing this not to mention during runtime it is very slow. I'm fairly sure Spring doesn't even support this (I mean it scans across component annotations but doesn't impose hierarchy that I know of based on packages).

I probably could add compiler flags to mimic module level config but I figured that most folks would just put all their templates and corresponding models in one or two places. To be honest I'm surprised it is that much of an inconvenience but I suppose if you have a highly featured oriented organization this happens.

Perhaps you can show me some examples of how painful this is?

At one point we were looking into providing custom annotations in which you could aggregate configuration similar to Spring custom annotation support. I would prefer that approach over recursing up the package tree and catching all the errors that happen.

**Comment by agentgt** [comment]
Anyway I probably could get it to work at compile time by prescanning for all the configuration annotations but its the runtime API that fallsback into using reflection that is nontrivial without some sort of external index or just brute very slow traversal.

I have a fairly decoupled and low opinionated philosophy of library development (hell the library has a zero dep option of no dependencies at all) but one thing I want to encourage more folks to do is properly modularize their application aka use `module-info.java` and if one cares that much about organization of components such that it is painful to put config in multiple places they absolutely should be using modules (`module-info.java`).

**Comment by dsyer** [comment]
I know that packages are not really hierarchical in the Java language, but they are in the file system (and on the classpath). Spring handles this by locating sub-packages using the class loader. It might have to be a different trick for an APT processor where there is no classpath at build time, but all the information is available at build time for sure, so it's a solvable problem. 

This is probably not the right place for a discussion of the merits of the module system. Modules are nice in theory, but most libraries do not use them, so developing applications that do is kind of a futile gesture. I understand that some people, yourself included, wish this wasn't the case, but in practical terms it's what we are stuck with.

One of the main reasons I am interested in JStachio is for native images, but Spring AOT doesn't work with module-info (and there doesn't seem to be any appetite to fix it: https://github.com/spring-projects/spring-boot/issues/33383), so making it compulsory is going to be a problem.

**Comment by agentgt** [comment]
Those are good points.

I’m just not sure how I can make it work for both reflection and APT.

The APT part is pretty straightforward. 

I suppose I can make it work for only compile time and just not have reflective lookup for that case since it is Spring Native.

Probably the easiest thing is a class reference to some other class that has the config which approaches custom annotations.

So you still would have to use package info on each package but it would be more concise (eg no dupe except for the reference).

Will that make it better?

**Comment by dsyer** [comment]
No dupe is the goal. I'd be happy enumerating the packages to include in the top level for instance.

**Comment by agentgt** [comment]
Using Petclinic as an example:


We have a class called `org.springframework.samples.system.MyJStacheConfig`

```
@JStacheConfig(...) // all standard config here
class MyJStacheConfig {
}
```

Then in the `org.springframework.samples.vet.package-info.java`

```java
import org.springframework.samples.system.MyJStacheConfig;

@JStacheConfig(ref=MyJStacheConfig.class)
package org.springframework.samples.vet;
```

and `org.springframework.samples.owner.package-info.java`

```java
import org.springframework.samples.system.MyJStacheConfig;

@JStacheConfig(ref=MyJStacheConfig.class)
package org.springframework.samples.owner;
```

I guess if the problem is making `package-info.java` I will have a hard time fixing that but even then you could in each class just put `@JStacheConfig(ref=MyJStacheConfig.class)`.


```java
package org.springframework.samples.owner;

@JStache(path=...)
@JStacheConfig(ref=MyJStacheConfig.class)
public record CreateOrUpdateOwnerForm() {
}
```

And if the extra annotation is a problem we could do:

```java
package org.springframework.samples.owner;

@JStache(path=..., config=MyJStacheConfig.class)
public record CreateOrUpdateOwnerForm() {
}
```

How is that? 

BTW although it is painful for `package-info` for every package you are technically supposed to do it for JSpecify and other TYPE_USE like nullable annotations. So I feel the pain but you kind of have to do it anyway and is encouraged by the javadoc system.

**Comment by agentgt** [comment]
> 
No dupe is the goal. I'd be happy enumerating the packages to include in the top level for instance.

The problem is I don't know where the top level is. That is kind of the problem that modules solve (I'm not trying to harp on it and I apologize on my foisted evangelism on it before).

I could make it a compiler flag but then it isn't available to the reflection based lookup which is useful for hot reload template development (however at the moment parent inheritance doesn't work with JMustache so it wouldn't work for you).

Also packages unlike classes don't have a type safe annotation friendly symbol for them (aka instead of a class reference it is just a String).

**Comment by agentgt** [comment]
I'm really liking the class reference config option because it will work across compile time boundaries (and or modules).

For example you could make a `config` module (maven or jpms aka jar) that has a class with all the `JStacheConfig` in it and share it across all your projects.

I planned on adding more power to JStachePath to help on template path resolution such as converting camel case to kebob or snake case etc. If we add enough power to `JStacheConfig` then you could even omit the `path` parameter from `JStache`.

Then all your model classes will just have the single annotation:

`@JStache(conf=MyJStacheConfig.class)`

Regardless of packages and modules I think the above is useful and is a good stopgap of providing custom annotations or some SPI that gets loaded by both APT and reflection.

**Comment by dsyer** [comment]
I'll give it a try. There's no way to set `@JStacheFormatterTypes` on a `@JStacheConfig` class though? I have a pretty hazy idea of what that does, but by trial and error I seem to need it to be able to render enums and dates.

**Comment by dsyer** [comment]
Just realized, I can't try it because it doesn't exist yet. Would be nice I think if a class could be marked with all of the `@JStache*` config annotations and then referred to from a package declaration via `@JStacheConfig`.

**Comment by agentgt** [comment]
Yeah the reasoning behind that is `JStacheFormatterTypes` is retention=SOURCE for the zero dep minimal footprint option.

I didn't know if it was more confusing to add it to JStacheConfig as well. JStacheConfig is more for runtime configuration and consequently it's rentention=RUNTIME but it seems reasonable to add it there as well.

**Comment by agentgt** [comment]
In the meantime for enums you can do:

```
{{myEnum.name}}
```

and it should work assuming you want the name.

**Comment by agentgt** [comment]
We should probably include formatter types in the Spring example app.

**Comment by agentgt** [comment]
Yeah the ergonomics of JStacheFormatterTypes and JStacheFormatter should be improved.

Current you can only have one `JStacheFormatter` and the `JStacheFormatterTypes` just allows whitelisting of `toString` on types.

So for you to do `LocalDateTime` for example you would have to register a `JStacheFormatter` that will handle LocalDateTime to no just `toString` and whitelist `LocalDateTime` on `JStacheFormatterTypes`.

This was partly residual of the older static-mustache. It should be easier than the above and you should be able to register multiple `JStacheFormatter` like a composite formatter.

**Comment by dsyer** [comment]
I still don't understand `@JStacheConfig`. I want to write 

```java
@JStachePath(prefix = "templates/", suffix = ".mustache")
@JStacheFlags(flags = Flag.DEBUG)
@JStacheFormatterTypes(types = LocalDate.class)
public class MyConfig {}
```

and then in `package-info.java` in all packages containing `@JStache` models:

```java
@JStacheConfig(types = MyConfig.class)
package com.example;
```

It doesn't seem to matter to me which annotations are runtime and which ones are source retention because `MyConfig` is always available in both places.

Maybe we need a new annotation?

**Comment by dsyer** [comment]
Aside: Spring has a `ConversionService` that we could probably wrap into a `JStacheFormatter` that could convert a large range of things to `String`. That wouldn't help with the whitelisting though (should be automated somehow to improve the ergonomics). Seems like a separate issue.

**Comment by agentgt** [comment]
Yeah JStacheConfig can’t reference other annotated classes yet.

The idea was to make all config in JStacheConfig and JStachePath being independent is sort of vestigial.

So yes JStacheConfig needs some more work.

Let me see if I can get a draft change in for discussion sometime next week via discord.

**Comment by agentgt** [comment]
So using your example

```java
@JStachePath(prefix = "templates/", suffix = ".mustache")
@JStacheFlags(flags = Flag.DEBUG)
@JStacheFormatterTypes(types = LocalDate.class)
public class MyConfig {}
```

Should be in 1.0.0 pre release (RC):

```java
@JStacheConfig(
pathing=@JStachePath(prefix = "templates/", suffix = ".mustache"), // <-- this exists
flags=@JStacheFlags(flags = Flag.DEBUG), // <-- this does not and I'm not sure I will add it
formatterTypes=@JStacheFormatterTypes(types = LocalDate.class) // <-- this param does not exist yet
formatter=SpringConversionAwareFormatter.class // <-- this parameter exists but not the implementation
)
public class MyConfig {}
```

Then where ever you can just reference `MyConfig.class` from either `JStache` or  another `JStacheConfig` perhaps package level.


See `JStacheConfig` came a little late to the game. I realized that it was confusing having gallons of annotations for API explorability and it is easier to have a single config annotation.

You are correct about how the retention does not matter but my point of it was that there are configuration things you want to control during compile time which is the camp that `JStacheFormatterTypes` is and then there are things that happen during runtime which is the camp `JStacheFormatter` and indeed there is overlap. I admit that dichotomy is confusing and thought being explicit about it would help ameliorate the confusion but it looks to be not the case. 

Ultimately there may need to be some SPI that can be activated at both compile time and runtime to make formatting registration easier and less error prone but I'm not sure if that is a good 1.0 target (I rather fix the parent partial problem first anyway).

However the deduping of config via class reference is very doable and adding more parameters to JStacheConfig as well.

**Comment by agentgt** [comment]
I quick thought to remove the pain and errors of registering both for formatterTypes and formatter is to have formatterTypes annotation on the formatter class itself. Then if you have the formatter picked the types will be pulled in as well.

Thus formatterTypes would not live on JStacheConfig but the formatter (provider) itself.

```java
@JStacheFormatter
@JStacheFormatterTypes(...)
public class MyFormatter implements Formatter {
}
```

It is an interesting feature to potentially allow multiple formatters but I think a DI framework is far more capable of solving that problem (to your point of Spring Conversion service). At least with the above the types and how they are converted are located in the same place.

**Comment by dsyer** [comment]
+1 to the `Formatter` annotations.

But I still hate `@JStacheConfig`. It's ugly, and it duplicates all that stuff that is already available as type/package level annotations. And then the stuff it doesn't duplicate is frustratingly missing. I see what you mean about a single point of discovery, but it's not a good enough reason IMO.

**Comment by agentgt** [comment]
Yes the dupe (feature wise) is unfortunate.

It is still useful though as a meta annotation for the class config reference.

I suppose I could explore some solution of getting rid of it but it is sad because it was supposed to make config resolution easier to understand and easier to implement.

And with the exception of formatter types it’s all in JStacheConfig.

And as we saw formatter types really should be mixed with formatters.

**Comment by agentgt** [comment]
I guess JStacheInterfaces is missing as well.

I went back and forth on JStacheConfig when I introduced it because: 

* Needed a place for existing and future ancillary, adhoc and auxiliary config like "charset" (like the class problem of the "Utils.java")
* A single place to document the cascading of config
* API explorability
* Simplification of reflective config lookup so that meta data lookup will do the same as APT

Where it got messed up is I could not decide whether to limit things like JStachePath to only be an argument to JStacheConfig or let it live on as able to be placed on the types/packages directly (because of previous releases) like most are currently using it.

Now I'm not sure what to do with it now based on your feedback. 

Maybe its parameters (e.g. naming) get removed and it is only an annotation to mark classes used for configuration (of course that begs the question if you even need such a marker).

Let's assume the class config reference works (e.g. `@JStache(conf=SomeClassWithAnnotations.class)`) and you can annotate that class with the regular annotations instead of JStacheConfig do you think that would get you closer to what you desire?

**Comment by dsyer** [comment]
> do you think that would get you closer to what you desire?

Closer, maybe, but still pretty horrible - most apps will have many more times models/pages than packages, and every model in the same package would likely have the same annotation. Yuck.

**Comment by agentgt** [comment]
> Closer, maybe, but still pretty horrible - most apps will have many more times models/pages than packages, and every model in the same package would likely have the same annotation. Yuck

It just hasn't been my experience that folks spread their views (templates) all over the place. I get feature packaging like in Petclinic where all things Vet for example are in the package "vet" including entities, services, controllers, etc but from my experience in the real world people do not do that for a variety of reasons.

Furthermore applications are becoming less monolithic. For example using the Petclinic app in the real world these days many would have split the "owner" from the "vet" into two applications which would require the config twice regardless (well it will be better with config class references but you still need to reference twice).

Perhaps you can point to me some example apps where this is the case?

> and every model in the same package would likely have the same annotation. Yuck

You only need config per package (or even better module). That works today. The number of times you need to duplicate is the number of packages you want to use. 
And if you forget its not like this it will silently fail at runtime like a plethora of other libraries. It will fail at build time if the config is not correct (ie JStachePath).

Furthermore other annotation libraries are way way more tedious. For example Jackson (can pull some examples later if you like on how painful it is). 
Even MapStruct is fairly high duplication of config.

I'm just saying your expectations might be a little too high if adding a one line annotation to each package-info is too painful especially if we do get the config reference work in (e.g. `@JStacheConfig(ref=MyClassWithAnnotations.class) package some.package;`)

And finally yeah I get people don't like modules but you can just just strip module-info at build time if that is a problem with native builds.

Otherwise the only solution I can think of is compiler flags (ie some arg in the maven/gradle apt section that says where the top level config is) which if you thought the dichotomy of having JStacheConfig (ie two ways to configure) is bad I think that would add even more confusion.

I know I sound a little contentious above but I'm wondering if this might be just bikeshedding over something very few will need and perhaps the defaults are what is wrong. 

Perhaps a custom Spring JStache annotation is needed that just does the config in an opinionated way that is OOB and works with boot. That is custom annotation work that I plan on doing after 1.0. See #42

**Comment by dsyer** [comment]
> I'm just saying your expectations might be a little too high if adding a one line annotation to each package-info is too painful

That would be great. I thought you were suggesting one per model class.

I suppose if the annotations are backed by a solid API we could provide Spring Boot support in other ways that make sense for those users (e.g. an annotation that applies to sub-packages, or just regular `application.properties` binding). I don't know enough about the internals of Jstachio to say if that is an option. Maybe I'll play around with it a bit.

**Comment by agentgt** [comment]
I’ll get some changes in the next couple of days and we can discuss via discord.

**Comment by agentgt** [comment]
@dsyer see #76 and #77. I have added `@JStacheConfig.using` which is essentially an import of config. You can review the javadoc here: https://jstach.io/jstachio/io.jstach.jstache/io/jstach/jstache/JStacheConfig.html

I also add `JStacheInterfaces` to `JStacheConfig` but you can continue to use it like `JStachePath` directly on a type/package/module. I have just accepted the fact that we have two ways to do it (the direct annotation takes precedence). Importing should work as well for that case (in fact the imported class doesn't even need `JStacheConfig`).

I also made it so formatterTypes can live on the formatter and doc is here:
https://jstach.io/jstachio/io.jstach.jstache/io/jstach/jstache/JStacheFormatter.html

I think these changes will get you largely what you want to deduping/drift of config.

Let me know if you want me to pump out a release for you to try it.

In the meantime I will fix the much harder issue of parent partials in blocks.

**Comment by dsyer** [comment]
> Let me know if you want me to pump out a release for you to try it.

Thanks. I can work with snapshots. Any chance of merging #74? Maybe get rid of `ViewFactory`?

**Comment by dsyer** [comment]
Seems to work for me, thanks. I like the way that `@JStacheFormatterTypes` is cumulative (you can add local classes in their own package).

**Comment by agentgt** [comment]
> Seems to work for me, thanks. I like the way that @JStacheFormatterTypes is cumulative (you can add local classes in their own package).

I think you probably meant this but it is only cumulative if its on a `@JStacheFormatter`. That is only one `@JStacheFormatterTypes` that isn't on a `@JStacheFormatter` is picked up and then is combined with what ever is on the formatter.

**Comment by dsyer** [comment]
I don't have a formatter or a `@JStacheFormatter`. I do have 3 `@JStacheFormatterTypes` (one on the "main" config class, and one each in the 2 packages that need additional hints). It seems to work, so I hope it was intentional. If not, then I guess that's a feature request,

**Comment by agentgt** [comment]
Then apparently I mis documented that. I will just change the doc to reflect that.

**Comment by agentgt** [comment]
I added #74 and made some minor fixes with javadoc. The normal build apparently does not check javadoc as thoroughly as I thought but the pages action does. I'm not sure why I did that.

**Comment by agentgt** [comment]
I think we have a good enough solution with JStacheConfig#using for now.
